{% set version = "1.2.1" %}

package:
  name: dose
  version: {{ version }}

source:
  fn: dose-{{ version }}.tar.gz
  url:  https://pypi.io/packages/source/d/dose/dose-{{ version }}.tar.gz
  sha256: 49ca085451324d524177c5c188f95bccd3ef8d96b64ce1094b285b733150e38f

build:
  number: 1000
  # We can drop this skip when we add wxpython-phoenix.
  skip: True  # [py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - dose = dose.__main__:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - watchdog >=0.6.0
    - colorama >=0.3.7
    - docutils >=0.12
    - wxpython

test:
  files:
    - dose_import_test.py
  commands:
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python dose_import_test.py'  # [linux]

about:
  home: http://github.com/danilobellini/dose
  license: GPL-3.0
  summary: 'Automated traffic light/signal/semaphore GUI showing the state during test driven development (TDD), mainly written for coding dojos.'
  license_family: GPL3

extra:
  recipe-maintainers:
    - ocefpaf
