appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CDYHD5zEOGabGnGupORGbVkqTadrAo4kbktF3mF1PnIFe4OmYwhTayQTDcAOfYGZiW0CSqsw0bWu7/NoPnvWlqKAxgVmf7/9lUDndjR+MZr7kQbfCc3pHSjpS1PBXYvrIzeogoljqmO37vFttdVVIIAdlJcG5gE5CZ1tczlUTsrJWd4d9nRihtYRCzuLqUXACnlGJuYmVu1rYr+ecKSIMilpDRarKnSptkApm+/sZzhUweMMlIwur89GUuimKeRHbm2ou0wVXGKLwJxaUNCPO4+2lj6Q0Ja1bem/B9Jz/dgD9YP2UlqU3WXSdu6PlJTJCI1FuHcSwrCtVQgRcSD9oBqcWkC/VO8pXGmkp1SMwR89ts8MKsvZO08pOSZF/4ARFy5g/LwMbYnbhpdlBDkN0+1fXIxxE4gOluXGwJddPhAXicyaHOyQk2+wYPndPdHS23G59nImbIF1NaEWx20B/TH4WjWKw0O4RRC/E+XvA6y/6xxPT4OGAfIyBkMEARg2SlX/g5OgRPynxUGvLH6KuMuL6Xle93mGdZleSh0I0U/5zX1sHzDoLjjWtWkXZTTw8xuXAj9Xlpfcnp8nNMWjwnnNh1hWbSyqp8jQrq6FdrAfsaW9aJyeWlYPPBDLc8dyz8fMH63PSUqD0j4t1xmPkRaPMEmMycsa1CeH5DlPRX0=}
conda_forge_output_validation: true
