travis:
  secure:
    BINSTAR_TOKEN: mSkH6oGrokB2CN7tct7iT75yUqUNMl/KWkmdQ81XNDG2nENLW5c8skY4GppazsgW4fv3hD9TdFX4UiX/R438rP7XW5ZYPSkNGw8b3PuRLl+cZ02S3g510+F1EfySRLiPSEIQCyw8i30I3BqSQCe6iziXNBDuTxQquLxw3AhjXxgc4JZR10tFsRH/zCpDyMYT+TtwUtzRNeG9YNjkTji/YQ0Nh3C2imgqRefl/10PWhpyJ9kddEd6OY+ULnXA3A47Wh5+1WXsjD3YKepFdm4HEw6tqlqBJOHQpymxzvQ2KtmYiOWZKdpd/3lzjDm6jvUCgLfXEpsTToWWiCaej0XDZh8abBN2GXRI1dkmTQdIieGoS4HSPbK0JsneQO69Q9/0H5Jf0LXD+a8U9SGn2LbyeSlcBnXwcDeavFrXnsJHu4CTc0wJvYd/fIxlzFB74gUXh5O4e8OnjhDFA8zluQcmrMgZ6VrY7+uwIN641qi/tMCDx/Jkz3A5yrwH53tk/vltVSEqZlL9hf5SJG1J6sYNHmat7JNCUkkvgbaY/dFpjjiqV7CN8O1/+IjeW8u8DRvQyQcgHZIL2ySzzz/im3YmhCZg42rP+9AEd9GTOrLv5518fjKInbtU5QgQVrhJF7UC69zHGwWI2XXeeN3FELACHDV6jShMjMjrDphBmj47t9s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
